GET http://localhost:3500/user/get-users

###
GET http://localhost:3500/user/get-user/sample
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjg4MzA5ODAwLCJleHAiOjE2ODgzMDk4MjB9.br-n6nrKyigYRVrJEdDdyOcgmSqm8KjItoWzLZQl6-U
###
POST http://localhost:3500/user/user-signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3500/user/user-login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###
PUT http://localhost:3500/user/update-user
Content-Type: application/json

{
    "id":100,
    "name":"Ramya Kumar",
    "age":25
}

###
DELETE http://localhost:3500/user/delete-user/200
